# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  # The name defines how the plugin is invoked, A unique name
  name: plugin-verse
spec:
  enabled: true
  requires: ">=2.20.0"
  author:
    name: University of Fool
    website: https://github.com/University-Of-Fool
  logo: logo.png
  homepage: https://github.com/University-Of-Fool/halo-plugin-verse
  repo: https://github.com/University-Of-Fool/halo-plugin-verse
  issues: https://github.com/University-Of-Fool/halo-plugin-verse/issues
  displayName: "诗篇"
  description: "为默认编辑器添加诗歌块"
  license:
    - name: "MIT"
      url: "https://github.com/University-Of-Fool/halo-plugin-verse/blob/main/LICENSE"
